[manager]

prepend_keymap = [
	{ on = "\\",       run = "quit",        desc = "Quit the process" },
	{ on = "<C-Up>",   run = "arrow -50%",  desc = "Move cursor up half page" },
	{ on = "<C-Down>", run = "arrow 50%",   desc = "Move cursor down half page" },
]
