#!/bin/bash

SOURCE="$1"
TARGET="$2"
SOCKET_FILE="$3"

echo "copying gitignored files"

(cd "$SOURCE" && git status --ignored -s | grep '^!! ' | awk '{print $2}') | while read filename; do
  echo "copying: $filename"
  cp -Rc "$SOURCE/$filename" "$TARGET/$filename"
done

if [ -f "$SOURCE/pnpm-lock.yaml" ]; then
  echo "running pnpm i"
  cd "$TARGET" && pnpm i
fi

if [ -n "$SOCKET_FILE" ]; then
  echo "restarting nvim LSP"
  nvim --server "$SOCKET_FILE" --remote-expr "v:lua.require'utils'.restart_lsp()"
fi
