#!/bin/bash

source "$(dirname "$0")/tmuxSetupWindows"

if [ "$#" -eq 0 ]; then
  cato << EOF
Usage examples:

  wtb new-branch-and-dirname
    # Creates a new branch with the given name

  wtb new-branch-and-dirname local-branch
    # Creates a new branch from another local branch

  wtb feature-branch origin/feature-branch
    # Creates a worktree from a remote branch with the same name

  wtb new-branch-and-dirname origin/remote-branch
    # Creates a new branch from a remote branch
EOF
  return 1
fi


SOURCE=$(realpath .)
TARGET="$SOURCE/../$1"

if [ -n "$2" ]; then
  if [[ "$2" == */* ]]; then
    REMOTE=$(echo "$2" | cut -d'/' -f1)
    BRANCH=$(echo "$2" | cut -d'/' -f2-)
    echo "Fetching remote branch $2..."
    git fetch "$REMOTE" "$BRANCH"
  fi
  git worktree add "$TARGET" "$2"
else
  git worktree add "$TARGET"
fi


TMUX_SESSION=$(create_worktree_session $(realpath "$TARGET"))
SOCKET_FILE=$(setup_tmux_windows "$TMUX_SESSION")


tmux send-keys -t "${TMUX_SESSION}:long" "$(dirname "$0")/worktreeBranchSetup \"$SOURCE\" \"$TARGET\" \"$SOCKET_FILE\"" Enter
